# Generated by Django 3.1.3 on 2023-06-02 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybo', '0010_auto_20230602_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='answer_voter',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='question_voter',
        ),
        migrations.AddField(
            model_name='comment',
            name='voter',
            field=models.ManyToManyField(related_name='comment_voter', to=settings.AUTH_USER_MODEL),
        ),
    ]
