# Generated by Django 3.1.3 on 2023-06-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0013_comment_modify_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='modify_count',
            new_name='answer_modify_count',
        ),
        migrations.AddField(
            model_name='comment',
            name='question_modify_count',
            field=models.IntegerField(default=0),
        ),
    ]
